spring:
  application:
    name: config
  threads:
   virtual:
    enabled: true
 rabbitmq:
  addresses: localhost
  username: guest
  password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
