spring:
  application:
    name: config
  threads:
   virtual:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  rabbitmq:
    addresses: localhost
    stream:
      username: guest
      password: guest
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: "*"
